# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='commented_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_on',
            new_name='commented_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_to',
            new_name='commented_to',
        ),
    ]
